[7] Ajout de template github
kungfuwushu/frontend pull request #19
Opened 2018-12-31 16:42 UTC by gcoutable

Ces templates ont pour but de guider le développeur lors de la création de :
- bug reports
- Feature Requests
- Regression reports

2019-01-07 20:11 UTC, frejfrej commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +* [ ] Reportes tu ce bug sur le bon repository ?
bug ?

2019-01-07 20:11 UTC, frejfrej commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +* [ ] As tu vérifié que ce bug n'existait pas déjà ?
feature? Ou demande d'évolution?

2019-01-07 20:11 UTC, frejfrej commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +Autres:
Ceci ne devrait-il pas être une rubrique (## Autres) ?

2019-01-07 20:11 UTC, frejfrej commented on .github/ISSUE_TEMPLATE/Regression.md
> +## Comportement attendu
J'imagine que "comportement précédent" décrit déjà cela ?

2019-01-07 20:16 UTC, frejfrej reviewed
En fait, je me demandais si nous devrions pas travailler en anglais pour permettre à la fédération qui travaille avec Nassim d'exploiter plus facilement nos travaux ?

2019-01-07 21:52 UTC, gcoutable commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +* [ ] Reportes tu ce bug sur le bon repository ?
mauvais copier/coller :p

2019-01-07 21:53 UTC, gcoutable commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +* [ ] As tu vérifié que ce bug n'existait pas déjà ?
Pareil!

2019-01-07 22:00 UTC, gcoutable commented on .github/ISSUE_TEMPLATE/Feature_request.md
> +Autres:
Dans le cas de la Feature request, vu la description, je dirais que oui, `Autres` devrait être une section.
Peut-être même que la section Environnement n'est pas non plus très pertinantes.

2019-01-07 22:02 UTC, gcoutable commented on .github/ISSUE_TEMPLATE/Regression.md
> +## Comportement attendu
ça dépend, si le "comportement attendu" n'est pas le "comportement précédent"

2019-01-07 22:04 UTC, gcoutable commented
Je peux proposer les templates en anglais. Ceux que je viens de proposer sont une traduction depuis l'anglais. (Peut-être que ça s'est vu :p)

2019-01-20 08:03 UTC, frejfrej requested changes
Peux-tu traiter les demandes de modifications stp ? En outre, pourras-tu les reporter sur le repo backend ?

2019-02-03 08:29 UTC, merged